export { default as Account } from './Account';
export { default as App } from './App';
export { default as Collections } from './Collections';
export { default as Earn } from './Earn';
export { default as Polls } from './Polls';
export { default as ErrorPage } from './error-page';
export { default as AddCollection } from './AddCollection';
export { default as UsersCollections } from './UsersCollections';
export { default as PollsHistory } from './PollsHistory';